title: mimo.blog
tagline: My personal blog for research notes and devlogs
description: A personal blog by mimocha, including random research notes and various devlogs.
github:
  username: mimocha
  profile: https://github.com/mimocha
author:
  name: Chawit Leosrisook
  url-home: https://mimocha.github.io/
  url-blog: https://mimocha.github.io/blog/

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-toc

baseurl: "/blog"

excluded:
  - README.md
  - LICENSE
  - .gitignore