title: mimo.blog
tagline: A collection of random thoughts, distilled for future reference.
description: A personal blog by mimocha, including random research notes and various development logs.
show_downloads: false

theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

baseurl: "/blog"