title: mimo.blog
tagline: My personal blog and collection of random research notes and devlogs
description: A personal blog by Chawit Leosrisook, including random research notes and various devlogs.
github:
  username: mimocha
  profile: https://github.com/mimocha
author:
  name: Chawit Leosrisook
  url-home: https://mimocha.github.io/
  url-blog: https://mimocha.github.io/blog/

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

baseurl: "/blog"

excluded:
  - README.md
  - LICENSE
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock